# Jekyll configuration

name: Trump, Politics, and Empires
description: A blog about modern politics and empires, both historical and modern

# url is currently only used only for the RSS feed in feed.xml
url: https://thatSteveFan.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: '/thatSteveFan.github.io'
## default date_format
date_format: 
  title: "%a: %B-%-d-%Y %l%p"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "en" 

paginate: 10


highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate', 'jekyll-compose']

exclude: ['README.md', 'LICENSE', "*.bak"]
